replicaCount: 2

image:
  repository: your-ecr-uri/auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

config:
  DATABASE_URL: "postgres://user:password@db:5432/equb"
  JWT_SECRET: "changeme"

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi